# SCALARS AND INPUTS
# ------
scalar Date
scalar Media

input QuestionInput {
    game: String!
    question: String
    choices: [String]
    answer: String
}

input GameDataInput {
    name: String
    subject: String
    exhibit: String
}

input UserInput {
    grade: String
    dob: Date
}
# ------

# User Schemas
type User {
    token: String
    id: String!
    name: String!
    email: String!
    grade: String
    dob: Date
    badges: [Badge]!
    staff: Boolean!
    profilePicture: String!
}

#type Staff {
#    id: String!
#    name: String!
#    email: String!
#    phone_num: String!
#}

# Badge Schemas
type Badge {
    id: String!
    name: String!
    description: String!
    exhibit: Exhibit!
    type: String!
}

type Exhibit {
    id: String!
    name: String!
    description: String!
    game: Game!
    badge: Badge!
    image: String!
}

# Game Schemas - NEEDS TO BE EXPANDED!!!
type Game {
    id: String!
    name: String!
    subject: String!
    exhibit: Exhibit!
    questions: [TriviaQuestion]!
}

type TriviaQuestion {
    id: String!
    game: Game!
    question: String!
    choices: [String]!
    answer: String!
}

union Question = TriviaQuestion # use pipe operator to extend different question types
type Query {
    # User Queries
    getUser(id: String!): User!
    getUsers: [User]!

    # Staff Queries
    # getStaff(id: String!): Staff!
    # getStaffMembers: [Staff]!

    # Badge Queries
    getBadge(id: String!): Badge!
    getBadges: [Badge]!

    # Exhibit Queries
    getExhibit(id: String!): Exhibit!
    getExhibits: [Exhibit]!

    # Game Queries
    getGame(id: String!): Game!
    getGames: [Game]!

    checkQuestion(id: String!, answer: String!): Boolean!
}

type Mutation {
    # User Mutations
    generateGoogleAuthURL: String!
    login(code: String!): User!

    createOrUpdateUser(input: UserInput): User!

    awardBadge(id: String!): User!

    deleteUser(id: String!): User!

    #updateUser(
    #    id: String!,
    #    name: String,
    #    email: String,
    #    grade: String,
    #   dob: Date
    #): User!

    # Staff Mutations
    #createStaff(
    #    name: String!,
    #    email: String!,
    #    phone_num: String!
    #): Staff!

    #deleteStaff(id: String!): Staff!

    #updateStaff(
    #    id: String!,
    #    name: String,
    #    email: String,
    #    phone_num: String
    #): Staff!

    # Badge Mutations
    createBadge(name: String!, description: String!, type: String!): Badge!

    deleteBadge(id: String!): Badge!

    updateBadge(
        id: String!
        name: String
        description: String
        type: String
    ): Badge!

    # Exhibit Mutations
    createExhibit(name: String!, description: String!, image: String!): Exhibit!

    deleteExhibit(id: String!): Exhibit!

    updateExhibit(
        id: String!
        name: String
        description: String
        game: String
        image: String
    ): Exhibit!

    # Game Mutations
    createGame(input: GameDataInput!): Game!

    deleteGame(id: String!): Game!

    updateGame(id: String!, input: GameDataInput!): Game!

    createQuestion(input: QuestionInput!): TriviaQuestion!

    deleteQuestion(id: String!): TriviaQuestion!

    updateQuestion(id: String!, input: QuestionInput): TriviaQuestion!
}

# TO-DO:
#   - expand game schemas to accomodate different game types
